services:
  vue-app:
    build:
      context: .
      args:
        - NODE_ENV=production
        - DB_URI=${DB_URI}
    image: vue-wordl:latest
    pull_policy: build
    environment:
      - DB_URI
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true