version: '3.8'

services:
  vue-app:
    build:
      context: .
      args:
        - NODE_ENV=production
        - DB_URI=${DB_URI}
    image: vue-wordl:latest
    pull_policy: build
    networks:
      - nginx-proxy-manager_default
    ports:
      - "8080:80"

networks:
  nginx-proxy-manager_default:
    external: false