version: '3.8'

services:
  vue-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    image: vue-wordl:latest
    pull_policy: build
    environment:
      - NUXT_DB_URI=${DB_URI}
      - NUXT_THEME_API=${THEME_API:-https://wotd-theme.ryxwaer.com/api/theme}
    networks:
      - nginx-proxy-manager_default
    ports:
      - "8080:80"

networks:
  nginx-proxy-manager_default:
    external: true